### ISSUE TITLE
lirc-setup brocken

### ISSUE THREAD

**Issue by attuska** [uhulinux/ub-ubk3#102]
>attila@attila-pc:~$ lirc-setup
/usr/lib/python3.7/site-packages/lirc-setup/mvc_control.py:13: PyGIWarning: Gtk was imported without specifying a version first. Use gi.require_version('Gtk', '3.0') before import to ensure that the right version gets loaded.
  from gi.repository import Gtk         # pylint: disable=no-name-in-module
Traceback (most recent call last):
  File "/bin/lirc-setup", line 16, in <module>
    import mvc_control
  File "/usr/lib/python3.7/site-packages/lirc-setup/mvc_control.py", line 16, in <module>
    import choosers
  File "/usr/lib/python3.7/site-packages/lirc-setup/choosers.py", line 11, in <module>
    import mvc_model
  File "/usr/lib/python3.7/site-packages/lirc-setup/mvc_model.py", line 14, in <module>
    from lirc.database import Database
  File "/usr/lib/python3.7/site-packages/lirc/__init__.py", line 7, in <module>
    from .client import get_default_lircrc_path
  File "/usr/lib/python3.7/site-packages/lirc/client.py", line 37, in <module>
    import lirc.config
ModuleNotFoundError: No module named 'lirc.config'
attila@attila-pc:~$

**Comment by attuska** [comment]
A régebbi verziónál:
>attila@attila-pc:~$ lirc-setup
/usr/lib/python3.7/site-packages/lirc-setup/mvc_control.py:13: PyGIWarning: Gtk was imported without specifying a version first. Use gi.require_version('Gtk', '3.0') before import to ensure that the right version gets loaded.
  from gi.repository import Gtk         # pylint: disable=no-name-in-module
Traceback (most recent call last):
  File "/bin/lirc-setup", line 16, in <module>
    import mvc_control
  File "/usr/lib/python3.7/site-packages/lirc-setup/mvc_control.py", line 16, in <module>
    import choosers
  File "/usr/lib/python3.7/site-packages/lirc-setup/choosers.py", line 11, in <module>
    import mvc_model
  File "/usr/lib/python3.7/site-packages/lirc-setup/mvc_model.py", line 14, in <module>
    from lirc.database import Database
  File "/usr/lib/python3.7/site-packages/lirc/__init__.py", line 7, in <module>
    from .client import get_default_lircrc_path
  File "/usr/lib/python3.7/site-packages/lirc/client.py", line 38, in <module>
    import _client
ModuleNotFoundError: No module named '_client'
attila@attila-pc:~$ 

Erről van is temérdek hibajelzés (Példa Debian: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=923397) és egy nyitott upstream bugreport:
https://sourceforge.net/p/lirc/tickets/341/

Képtelen voltam megbírkózni vele.
A tevii-s470 dvbS2 kártyám infrája nem megy, néma a /dev/event13, csak UHU 2.2 alatt működik még mindig a távirányító.
A kernelbe be van építve az infra, de nem jó, néma. Nincs /dev/rc0 eszköz.
>root@attila-pc:~# ir-keytable
Found /sys/class/rc/rc0/ (/dev/input/event13) with:
	Name: cx23885 IR (TeVii S470)
	Driver: cx23885, table: rc-tevii-nec
	Supported kernel protocols: other rc-5 rc-5-sz jvc sony nec sanyo mce_kbd rc-6 sharp xmp imon 
	Enabled kernel protocols: rc-6 
	bus: 1, vendor/product: d470:9022, version: 0x0001
	Repeat delay = 500 ms, repeat period = 125 ms
root@attila-pc:~#

**Comment by attuska** [comment]
A 0.9.4d lirc-setup elindul, bejön a python gui, de a 0.9.10 már hibás.

**Comment by attuska** [comment]
UBK1 alatt vannak a /dev alatt rcx eszközök, a tevii távirányítója meg is tudja szólítani az egyiket. A dev/rc1 eszközöm a cat paranccsra  szépen krixkraxol, tehát beüzemelhető lehetne.
UBK3 és 4 alatt már nincsenek ilyen rcx eszközök, a kernelek nem regisztrálnak ilyeneket már a dmesg szerint.
Részlet:
>[    6.223654] rc rc0: cx23885 IR (TeVii S470) as /devices/pci0000:00/0000:00:07.0/0000:02:00.0/rc/rc0
[    6.223702] input: cx23885 IR (TeVii S470) as /devices/pci0000:00/0000:00:07.0/0000:02:00.0/rc/rc0/input15

 Ellenben a /dev/input15 a cat parancsra néma, ha nyomogatom a távirányító gombjait.

**Comment by attuska** [comment]
https://mauricius.dev/configure-an-infrared-remote-control-with-linux/
Az itt leírtak alapján már némi remény csillant fel:
>root@attila-pc:~# ir-keytable -v -t -p rc-5,rc-5-sz,jvc,sony,nec,sanyo,mce_kbd,rc-6,sharp,xmp
Found device /sys/class/rc/rc0/
Couldn't find any node at /sys/class/rc/rc0/lirc*.
Input sysfs node is /sys/class/rc/rc0/input15/
Event sysfs node is /sys/class/rc/rc0/input15/event13/
Parsing uevent /sys/class/rc/rc0/input15/event13/uevent
/sys/class/rc/rc0/input15/event13/uevent uevent MAJOR=13
/sys/class/rc/rc0/input15/event13/uevent uevent MINOR=77
/sys/class/rc/rc0/input15/event13/uevent uevent DEVNAME=input/event13
Parsing uevent /sys/class/rc/rc0/uevent
/sys/class/rc/rc0/uevent uevent NAME=rc-tevii-nec
/sys/class/rc/rc0/uevent uevent DRV_NAME=cx23885
/sys/class/rc/rc0/uevent uevent DEV_NAME=cx23885 IR (TeVii S470)
input device is /dev/input/event13
/sys/class/rc/rc0/protocols protocol rc-5 (disabled)
/sys/class/rc/rc0/protocols protocol nec (disabled)
/sys/class/rc/rc0/protocols protocol rc-6 (disabled)
/sys/class/rc/rc0/protocols protocol jvc (disabled)
/sys/class/rc/rc0/protocols protocol sony (disabled)
/sys/class/rc/rc0/protocols protocol rc-5-sz (disabled)
/sys/class/rc/rc0/protocols protocol sanyo (disabled)
/sys/class/rc/rc0/protocols protocol sharp (disabled)
/sys/class/rc/rc0/protocols protocol mce_kbd (disabled)
/sys/class/rc/rc0/protocols protocol xmp (disabled)
/sys/class/rc/rc0/protocols protocol imon (disabled)
/sys/class/rc/rc0/protocols protocol rc-mm (disabled)
Opening /dev/input/event13
Input Protocol version: 0x00010001
Protocols changed to rc-5 rc-5-sz jvc sony nec sanyo mce_kbd rc-6 sharp xmp 
Testing events. Please, press CTRL-C to abort.

És már reagál tesztre!

**Comment by attuska** [comment]
A VDR már beüzemelhető, csak sajnos pár fontos gombot nem érzékel. A teszt szerint viszont minden gombja rendben van és válaszol, kíiírja a helyes gombnevet.

**Comment by attuska** [comment]
Csak akkor él a távirányító, ha előtte engedélyezve lett a nec kernel protocol
ir-keytable -p nec
