### ISSUE TITLE
python3-automat hiba

### ISSUE THREAD

**Issue by attuska** [uhulinux/ub-ubk3#108]
python3-automat-0.8.3 :
>attila@attila-pc:~$ automat-visualize
Traceback (most recent call last):
  File "/bin/automat-visualize", line 11, in <module>
    load_entry_point('Automat==0.3.0', 'console_scripts', 'automat-visualize')()
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 479, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2860, in load_entry_point
    return ep.load()
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2464, in load
    return self.resolve()
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2470, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib/python3.7/site-packages/automat/_visualize.py", line 5, in <module>
    import graphviz
ModuleNotFoundError: No module named 'graphviz'
attila@attila-pc:~$ 

A frissített is így pofázik vissza.
(python3-automat-20.2.0)

**Comment by attuska** [comment]
Kellet neki egy új python3 csomag. https://github.com/uhulinux/ub-ubk3/commit/9389493d38b8a5b580c10ec7971bf19911d69150
Így már némiképp jobb, de nem sok értelmét látom ennek a python3-automat csomagnak, kétlem, hogy valakinikenk hiányozna, ha nem lenne.
