### ISSUE TITLE
runsnakerun hiba

### ISSUE THREAD

**Issue by attuska** [uhulinux/ub-ubk3#109]
attila@attila-pc:~$ runsnake
/usr/lib/python3.7/site-packages/runsnakerun/listviews.py:265: wxPyDeprecationWarning: Using deprecated class. Use ItemAttr instead
  indicated_attribute = wx.ListItemAttr()
12:12:15: Debug: Adding duplicate image handler for 'PNG file'
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/runsnakerun/runsnake.py", line 836, in OnInit
    frame = MainFrame(config_parser=load_config())
  File "/usr/lib/python3.7/site-packages/runsnakerun/runsnake.py", line 216, in __init__
    self.CreateControls(config_parser)
  File "/usr/lib/python3.7/site-packages/runsnakerun/runsnake.py", line 268, in CreateControls
    self.rightSplitter.SetSashSize(10)
AttributeError: 'SplitterWindow' object has no attribute 'SetSashSize'
OnInit returned false, exiting...
attila@attila-pc:~$

**Comment by attuska** [comment]
Sok lesz neki a wxpython-4.1.1 
Ezt ebből a nyitott issue-ből következtetem: https://github.com/mcfletch/runsnakerun/issues/3

**Comment by attuska** [comment]
Egy kis "javítás" : https://github.com/uhulinux/ub-ubk3/commit/5509da3965246642be960765676cd8256670214e
Egy még nem elfogadott pr kérést alkalmazva már valami van.

**Comment by attuska** [comment]
Kidobva.
https://github.com/uhulinux/ub-ubk3/commit/83c8a921f20fde9503913a1188e9eec4dc198ac3
