### ISSUE TITLE
deluge bug

### ISSUE THREAD

**Issue by attuska** [uhulinux/ub-ubk3#135]
ttila@attila-pc:/usr/src/UHUBUILD/UB-UBK3$ deluge
Traceback (most recent call last):
  File "/bin/deluge", line 33, in <module>
    sys.exit(load_entry_point('deluge==2.0.5', 'gui_scripts', 'deluge')())
  File "/usr/lib/python3.7/site-packages/deluge/ui/ui_entry.py", line 143, in start_ui
    ui.start()
  File "/usr/lib/python3.7/site-packages/deluge/ui/gtk3/__init__.py", line 48, in start
    from .gtkui import GtkUI
  File "/usr/lib/python3.7/site-packages/deluge/ui/gtk3/gtkui.py", line 50, in <module>
    from deluge.ui.client import client
  File "/usr/lib/python3.7/site-packages/deluge/ui/client.py", line 17, in <module>
    from twisted.internet import defer, reactor, ssl
  File "/usr/lib/python3.7/site-packages/twisted/internet/ssl.py", line 58, in <module>
    from OpenSSL import SSL  # type: ignore[import]
  File "/usr/lib/python3.7/site-packages/OpenSSL/__init__.py", line 8, in <module>
    from OpenSSL import crypto, SSL
  File "/usr/lib/python3.7/site-packages/OpenSSL/crypto.py", line 17, in <module>
    from OpenSSL._util import (
  File "/usr/lib/python3.7/site-packages/OpenSSL/_util.py", line 6, in <module>
    from cryptography.hazmat.bindings.openssl.binding import Binding
  File "/usr/lib/python3.7/site-packages/cryptography/hazmat/bindings/openssl/binding.py", line 14, in <module>
    from cryptography.hazmat.bindings._openssl import ffi, lib
ModuleNotFoundError: No module named 'cryptography.hazmat.bindings._openssl'
attila@attila-pc:/usr/src/UHUBUILD/UB-UBK3$

**Comment by attuska** [comment]
A cryptography visszafejlesztés helyrehozta.
https://github.com/uhulinux/ub-ubk3/commit/097dce98824f8ee46ef89bee82507c7366793a8d
