### ISSUE TITLE
gnome-schedule import error

### ISSUE THREAD

**Issue by attuska** [uhulinux/ub-ubk3#137]
`attila@attila-pc:~$ gnome-schedule
Traceback (most recent call last):
  File "/usr/share/gnome-schedule/gnome-schedule.py", line 27, in <module>
    import mainWindow
  File "/usr/share/gnome-schedule/mainWindow.py", line 25, in <module>
    import gtk.glade
ImportError: No module named glade
attila@attila-pc:~$ 
`

**Comment by attuska** [comment]
Ki lesz dobva ez a python2 marhaság.
https://bugzilla.redhat.com/show_bug.cgi?id=1087047

**Comment by attuska** [comment]
kidobva https://github.com/uhulinux/ub-ubk3/commit/eb7050d5043585bd6e0fc97c93193847211f8f75
