### ISSUE TITLE
Újrafordított pychess nem indul

### ISSUE THREAD

**Issue by attuska** [uhulinux/ub-ubk3#139]
Ez a hiba az újrafordítottnál:
`/usr/lib/python3.7/site-packages/pkg_resources/__init__.py:126: PkgResourcesDeprecationWarning: 2.02.186-2-.-2019-08-27- is an invalid version and will not be supported in a future release
  PkgResourcesDeprecationWarning,
Failed to create splash screen
Traceback (most recent call last):
  File "/bin/pychess", line 4, in <module>
    __import__('pkg_resources').run_script('PyChess==1.0.3', 'pychess')
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 672, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 1472, in run_script
    exec(code, namespace, namespace)
  File "/usr/lib/python3.7/site-packages/PyChess-1.0.3-py3.7.egg/EGG-INFO/scripts/pychess", line 97, in <module>
    from pychess.System.prefix import addDataPrefix, getDataPrefix, isInstalled
  File "/usr/lib/python3.7/site-packages/PyChess-1.0.3-py3.7.egg/pychess/System/prefix.py", line 27, in <module>
    raise Exception("can't find the pychess data directory")
Exception: can't find the pychess data directory
attila@attila-pc:~$`
A nem újrafordítottal nincs gond, szépen működik, a jelenkező hiba okát nem tudtam még kideríteni.

**Comment by attuska** [comment]
Gány megoldás, de lesz még jobb is: https://github.com/uhulinux/ub-ubk3/commit/57750358320e3808fb6243fb4543a9dae21d6fff
Valami miatt az adatok rossz helyre pakolódnak újabban.

**Comment by attuska** [comment]
Az install részben volt a légypiszok.
https://github.com/uhulinux/ub-ubk3/commit/20cc647566797acb5d0a40e018b3d4050db5fd42
