### ISSUE TITLE
dark-oberon crash

### ISSUE THREAD

**Issue by attuska** [uhulinux/ub-ubk3#48]
A glfw ablakban összeomlik.

> attila@attila-pc:~$ dark-oberon
Crit: Could not create mutex
Info: Loading configuration from '/home/attila/.dark-oberon/config.cfg'
Info: Loading data
Info: Loading textures from '/usr/share/games/dark-oberon/dat/fonts.dat'
Info: Loading textures from '/usr/share/games/dark-oberon/dat/gui.dat'
Info: Loading textures from '/usr/share/games/dark-oberon/dat/cursors.dat'
Info: Loading sounds from '/usr/share/games/dark-oberon/dat/gui.dat'
> Err: Unable to load Ogg file: 
>
> Err: Unable to load Ogg file: 
> 
> Err: Unable to load Ogg file: 
> 
> Err: Unable to load Ogg file: 
> 
>terminate called after throwing an instance of 'TSAVE_LIST<TCALLBACK>::MutexException'
Félbeszakítva (core készült)

gdb:

>terminate called after throwing an instance of 'TSAVE_LIST<TCALLBACK>::MutexException'
>
>Thread 1 "dark-oberon" received signal SIGABRT, Aborted.
0x00007ffff7759264 in raise () from /lib/libc.so.6
(gdb) bt
#0  0x00007ffff7759264 in raise () from /lib/libc.so.6
#1  0x00007ffff774450e in abort () from /lib/libc.so.6
#2  0x00007ffff7ae1662 in __gnu_cxx::__verbose_terminate_handler() [clone .cold] () from /usr/lib/libstdc++.so.6
#3  0x00007ffff7aed156 in __cxxabiv1::__terminate(void (*)()) () from /usr/lib/libstdc++.so.6
#4  0x00007ffff7aed1a1 in std::terminate() () from /usr/lib/libstdc++.so.6
#5  0x00007ffff7aed3d4 in __cxa_throw () from /usr/lib/libstdc++.so.6
#6  0x000000000047b5f5 in ?? ()
#7  0x00000000004063c6 in ?? ()
#8  0x00000000004067ed in ?? ()
#9  0x00007ffff774608e in __libc_start_main () from /lib/libc.so.6
#10 0x0000000000405cba in ?? ()
(gdb) q

A mutex az nem windóz specifikum?

**Comment by attuska** [comment]
A legújabb UBK3 -nál már megy.
