### ISSUE TITLE
vice: illegal instruction

### ISSUE THREAD

**Issue by attuska** [uhulinux/ub-ubk3#58]
Nem indul egyik része sem,  illegális utasításba futnak.
Példa:
>attila@attila-pc:~$ x64
Érvénytelen utasítás (core készült)

gdb:
>Starting program: /usr/bin/x64 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/libthread_db.so.1".
>
>Program received signal SIGILL, Illegal instruction.
0x000000000058ef79 in ?? ()
(gdb) bt
#0  0x000000000058ef79 in ?? ()
#1  0x00000000004de5b8 in ?? ()
#2  0x00000000004da799 in ?? ()
#3  0x000000000045b5f9 in ?? ()
#4  0x00000000004f05b7 in ?? ()
#5  0x0000000000430892 in ?? ()
#6  0x00007ffff685a08e in __libc_start_main () from /lib/libc.so.6
#7  0x000000000041920a in ?? ()
(gdb) q

**Comment by attuska** [comment]
Fix: https://github.com/uhulinux/ub-ubk3/commit/a9610d6696d97cbf074486b95c81335e6cc7ce24
Az eddigi O3 optimatizáció intel dual-core CPU által értelmezhetetlen utasítást eredményezett!
Lecserélve -O2 -re már nincs ilyen többé.

**Comment by attuska** [comment]
A full rebuild után ismét van!
attila@attila-pc:~$ x64
Érvénytelen utasítás (core készült)
attila@attila-pc:~$

**Comment by attuska** [comment]
Újraforgatva a csomagot helyrejött.

**Comment by attuska** [comment]
Újból előjött, illegális utasítás van a generált kódban.

**Comment by attuska** [comment]
Ismét újtaforgatva már működik a csomag.
