### ISSUE TITLE
worker segfault & avfs split bug

### ISSUE THREAD

**Issue by attuska** [uhulinux/ub-ubk3#59]
1. Az avfs hasítása hibás, mert felrántja a glibc-dev -et is! Ez kiküszöbölhető könnyedén, de mit sem használ, mert az avfs egyedül a worker-nek kellene, az meg hibás.
2. A worker szegmentációs hibával nem indul. Akkor sem, ha az avfs a fuse2 -vel van fordítva. a worker -O0 opimatizációval történt fordítása esetén is.
>(gdb) r
Starting program: /usr/bin/worker 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/libthread_db.so.1".
>
>Program received signal SIGSEGV, Segmentation fault.
0x00007ffff793eba6 in __strlen_sse2 () from /lib/libc.so.6
(gdb) bt
#0  0x00007ffff793eba6 in __strlen_sse2 () from /lib/libc.so.6
#1  0x00007ffff7dfaccd in av_new_avfs () from /usr/lib/libavfs.so.0
#2  0x00007ffff7e09e54 in av_init_filt () from /usr/lib/libavfs.so.0
#3  0x00007ffff7e1a691 in av_init_module_uzstde () from /usr/lib/libavfs.so.0
#4  0x00007ffff7e1acd0 in av_init_static_modules () from /usr/lib/libavfs.so.0
#5  0x00007ffff7dfec5b in av_get_ventry () from /usr/lib/libavfs.so.0
#6  0x00007ffff7e02f67 in open_path.constprop () from /usr/lib/libavfs.so.0
#7  0x00007ffff7e030ad in common_stat () from /usr/lib/libavfs.so.0
#8  0x000000000051a5f6 in ?? ()
#9  0x00000000004d1529 in ?? ()
#10 0x00000000004d1d29 in ?? ()
#11 0x00000000004d17c3 in ?? ()
#12 0x000000000050365b in ?? ()
#13 0x00000000004d9c03 in ?? ()
#14 0x00000000006a443d in ?? ()
#15 0x00000000006a7376 in ?? ()
#16 0x00007ffff78cd08e in __libc_start_main () from /lib/libc.so.6
#17 0x000000000040bc5a in ?? ()
(gdb)

**Comment by attuska** [comment]
Csak az avfs downgrade és azzal a worker újraforgatása rebuild rakta rendbe.
https://github.com/uhulinux/ub-ubk3/commit/1cc8bfc84ae8d84e3a4a74cad5c954029665bd82
https://github.com/uhulinux/ub-ubk3/commit/3b991197f073af571b962a09d8ea831af5298c1b
