### ISSUE TITLE
pitivi

### ISSUE THREAD

**Issue by attuska** [uhulinux/ub-ubk3#60]
>attila@attila-pc:~$ pitivi
HIBA – A következő szigorú függőségek nincsenek kielégítve:
===========================================================
– matplotlib nem található az Ön rendszerén
attila@attila-pc:~$ 

Pedig van python3 matplotlib!
Mind a pitivi, mind a python3-matplotlib csomag rendben lévőnek tűnik.

**Comment by attuska** [comment]
Mégsincs rendben a matplotlib.
>attila@attila-pc:~$ python3
Python 3.7.4 (default, Sep 28 2019, 10:19:34) 
[GCC 9.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import matplotlib
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.7/site-packages/matplotlib/__init__.py", line 205, in <module>
    _check_versions()
  File "/usr/lib/python3.7/site-packages/matplotlib/__init__.py", line 199, in _check_versions
    module = importlib.import_module(modname)
  File "/usr/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ModuleNotFoundError: No module named 'kiwisolver'
>>>

**Comment by attuska** [comment]
Megoldva.
https://github.com/uhulinux/ub-ubk3/commit/7629c8a2fc3a15291410cc72ce2d5c9fc43a8ca8
