### ISSUE TITLE
ghetto-skype start bug

### ISSUE THREAD

**Issue by attuska** [uhulinux/ub-ubk3#65]
>attila@attila-pc:~$ ghetto-skype
A JavaScript error occurred in the main process
Uncaught Exception:
Error: Unable to find a valid app
    at Object.<anonymous> (/usr/lib/ghetto-skype/resources/electron.asar/browser/init.js:121:9)
    at Object.<anonymous> (/usr/lib/ghetto-skype/resources/electron.asar/browser/init.js:173:3)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Function.Module.runMain (module.js:605:10)
    at startup (bootstrap_node.js:167:16)
    at bootstrap_node.js:589:3
attila@attila-pc:~$

**Comment by attuska** [comment]
A forrásból a browser.patch törlése után készült csomaggal elindul.

**Comment by attuska** [comment]
https://github.com/uhulinux/ub-ubk3/commit/89aea69c40e45fd77c218cfec58a64b0e4b864d3
