### ISSUE TITLE
retrovol segmentation fault

### ISSUE THREAD

**Issue by attuska** [uhulinux/ub-ubk3#73]
>(gdb) r
Starting program: /usr/bin/retrovol 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/libthread_db.so.1".
[Detaching after fork from child process 32375]
>
>Program received signal SIGSEGV, Segmentation fault.
0x00007ffff7649928 in signal_emit_unlocked_R ()
   from /usr/lib/libgobject-2.0.so.0
(gdb) bt
#0  0x00007ffff7649928 in signal_emit_unlocked_R ()
   from /usr/lib/libgobject-2.0.so.0
#1  0x00007ffff7654c9f in g_signal_emit_valist ()
   from /usr/lib/libgobject-2.0.so.0
#2  0x00007ffff765530f in g_signal_emit () from /usr/lib/libgobject-2.0.so.0
#3  0x00007ffff7b72032 in gtk_widget_hide () from /usr/lib/libgtk-x11-2.0.so.0
#4  0x0000000000585240 in ?? ()
#5  0x00007ffff7a545bb in _gtk_marshal_BOOLEAN__BOXED ()
   from /usr/lib/libgtk-x11-2.0.so.0
#6  0x00007ffff7637db2 in g_closure_invoke ()
   from /usr/lib/libgobject-2.0.so.0
#7  0x00007ffff764a743 in signal_emit_unlocked_R ()
   from /usr/lib/libgobject-2.0.so.0
#8  0x00007ffff765435a in g_signal_emit_valist ()
   from /usr/lib/libgobject-2.0.so.0
#9  0x00007ffff765530f in g_signal_emit () from /usr/lib/libgobject-2.0.so.0
#10 0x00007ffff7b6c4a4 in gtk_widget_event_internal ()
   from /usr/lib/libgtk-x11-2.0.so.0
#11 0x00007ffff7a52cc3 in gtk_main_do_event ()
   from /usr/lib/libgtk-x11-2.0.so.0
#12 0x00007ffff78bb72c in gdk_event_dispatch ()
   from /usr/lib/libgdk-x11-2.0.so.0
#13 0x00007ffff753366d in g_main_context_dispatch ()
--Type <RET> for more, q to quit, c to continue without paging--
   from /usr/lib/libglib-2.0.so.0
#14 0x00007ffff7533910 in g_main_context_iterate.isra ()
   from /usr/lib/libglib-2.0.so.0
#15 0x00007ffff7533be3 in g_main_loop_run () from /usr/lib/libglib-2.0.so.0
#16 0x00007ffff7a51c5a in gtk_main () from /usr/lib/libgtk-x11-2.0.so.0
#17 0x000000000040faf3 in ?? ()
#18 0x000000000040732a in ?? ()
#19 0x00007ffff6ff708e in __libc_start_main () from /lib/libc.so.6
#20 0x00000000004074ea in ?? ()
(gdb) q

**Comment by attuska** [comment]
Ez is a nem karbantartott forrásúak csoportjába tartozik, kidobásra méltó. 6 éve magára van hagyva, a csomagot csak a jwm használná runtime módon, ha tudná. Kidobása esetén a jwm csaomagot is módosítani kellene.
A szegmetációs hiba megszűntetését én reménytelennek látom.

**Comment by attuska** [comment]
UBK1/64 jó.

**Comment by attuska** [comment]
Kidobva. https://github.com/uhulinux/ub-ubk3/commit/541f374d8e0aede95c9d5ba470ae5734c36ce79a
