### ISSUE TITLE
audispd segfault

### ISSUE THREAD

**Issue by attuska** [uhulinux/ub-ubk3#8]
Nem megy, szegmentálási hibával végzi.

>root@attila-pc:~# audispd
Szegmentálási hiba (core készült)
root@attila-pc:~# gdb audispd
GNU gdb (GDB) 8.1.1
Copyright (C) 2018 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-gnu-linux".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from audispd...(no debugging symbols found)...done.
(gdb) r
Starting program: /sbin/audispd 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/libthread_db.so.1".
>
>Program received signal SIGSEGV, Segmentation fault.
0x00007ffff7e71e90 in opendir () from /lib/libc.so.6
(gdb) bt
#0  0x00007ffff7e71e90 in opendir () from /lib/libc.so.6
#1  0x0000555555558895 in load_plugin_conf ()
#2  0x0000555555557782 in main ()
(gdb)

**Comment by attuska** [comment]
Az audispd-plugins feltelepítése megszűnteti a szegmentálási hibát.

**Comment by attuska** [comment]
https://github.com/uhulinux/ub-ubk3/commit/2ec7e30c36c75c47427020c49e51c4a51f1139cc
Nem is értem, hogy ez miért 2 külön csomag? Fedora beidegződés?
