### ISSUE TITLE
apper crash

### ISSUE THREAD

**Issue by attuska** [uhulinux/ub-ubk3#81]
Bármely katagóriát választva összeomlik.
>attila@attila-pc:~$ apper
QCommandLineParser: option not defined: "install-provide-file"
apper: 
apper: 
apper.lib: group unrecognised:  PackageKit::Transaction::Group(35)
apper.lib: group unrecognised:  PackageKit::Transaction::Group(35)
apper: PackageKit::Transaction::RoleSearchGroup ""
void PackageModel::clear()
*** Error in `apper': free(): invalid pointer: 0x0000000002590043 ***
Félbeszakítva (core készült)
attila@attila-pc:~$

**Comment by attuska** [comment]
>(gdb) bt
#0  0x00007ffff5a661f4 in raise () from /lib/libc.so.6
#1  0x00007ffff5a5150e in abort () from /lib/libc.so.6
#2  0x00007ffff5aa6c18 in __libc_message () from /lib/libc.so.6
#3  0x00007ffff5aacf88 in malloc_printerr () from /lib/libc.so.6
#4  0x00007ffff4f89591 in g_hash_table_insert_node ()
   from /usr/lib/libglib-2.0.so.0
#5  0x00007ffff4f8ad0e in g_hash_table_insert ()
   from /usr/lib/libglib-2.0.so.0
#6  0x00007ffff509bae5 in as_xml_parse_metainfo_description_node ()
   from /usr/lib/libappstream.so.4
#7  0x00007ffff50abdb5 in as_component_load_from_xml ()
   from /usr/lib/libappstream.so.4
#8  0x00007ffff50a6535 in as_metadata_parse () from /usr/lib/libappstream.so.4
#9  0x00007ffff50a69cc in as_metadata_parse_file ()
   from /usr/lib/libappstream.so.4
#10 0x00007ffff50b3c6a in as_pool_load () from /usr/lib/libappstream.so.4
#11 0x00007ffff6481407 in AppStream::Pool::load() ()
   from /usr/lib/libAppStreamQt.so.2
#12 0x00007ffff64814df in AppStream::Pool::load(QString*) ()
   from /usr/lib/libAppStreamQt.so.2
#13 0x00007ffff7fb64c1 in AppStreamHelper::open() ()
   from /usr/lib/apper/libapper_private.so
#14 0x00007ffff7fb692d in AppStreamHelper::instance() ()
   from /usr/lib/apper/libapper_private.so
#15 0x00007ffff7fad3bd in PackageModel::addPackage(PackageKit::Transaction::Info, QString const&, QString const&, bool) [clone .part.0] ()
   from /usr/lib/apper/libapper_private.so
#16 0x00007ffff7fae0c0 in PackageModel::addPackage(PackageKit::Transaction::Info, QString const&, QString const&, bool) ()
   from /usr/lib/apper/libapper_private.so
#17 0x00007ffff61cbcd0 in QMetaObject::activate(QObject*, int, int, void**) ()
   from /usr/lib/qt5/lib/libQt5Core.so.5
#18 0x00007ffff7f0e41b in PackageKit::Transaction::package(PackageKit::Transaction::Info, QString const&, QString const&) ()
   from /usr/lib/libpackagekitqt5.so.1
#19 0x00007ffff7f104cc in PackageKit::Transaction::qt_static_metacall(QObject*, QMetaObject::Call, int, void**) () from /usr/lib/libpackagekitqt5.so.1
#20 0x00007ffff61cbb8b in QMetaObject::activate(QObject*, int, int, void**) ()
   from /usr/lib/qt5/lib/libQt5Core.so.5
#21 0x00007ffff7f28697 in OrgFreedesktopPackageKitTransactionInterface::qt_static_metacall(QObject*, QMetaObject::Call, int, void**) ()
   from /usr/lib/libpackagekitqt5.so.1
#22 0x00007ffff7f29e83 in OrgFreedesktopPackageKitTransactionInterface::qt_metacall(QMetaObject::Call, int, void**) () from /usr/lib/libpackagekitqt5.so.1
#23 0x00007ffff655c7db in ?? () from /usr/lib/qt5/lib/libQt5DBus.so.5
#24 0x00007ffff61cc95a in QObject::event(QEvent*) ()
   from /usr/lib/qt5/lib/libQt5Core.so.5
#25 0x00007ffff6c7ec62 in QApplicationPrivate::notify_helper(QObject*, QEvent*) () from /usr/lib/qt5/lib/libQt5Widgets.so.5
#26 0x00007ffff6c881e0 in QApplication::notify(QObject*, QEvent*) ()
   from /usr/lib/qt5/lib/libQt5Widgets.so.5
#27 0x00007ffff61a27e0 in QCoreApplication::notifyInternal2(QObject*, QEvent*)
    () from /usr/lib/qt5/lib/libQt5Core.so.5
#28 0x00007ffff61a5783 in QCoreApplicationPrivate::sendPostedEvents(QObject*, int, QThreadData*) () from /usr/lib/qt5/lib/libQt5Core.so.5
#29 0x00007ffff61f5e63 in ?? () from /usr/lib/qt5/lib/libQt5Core.so.5
#30 0x00007ffff4f9e66d in g_main_context_dispatch ()
   from /usr/lib/libglib-2.0.so.0
#31 0x00007ffff4f9e910 in g_main_context_iterate.isra ()
   from /usr/lib/libglib-2.0.so.0
#32 0x00007ffff4f9e99f in g_main_context_iteration ()
   from /usr/lib/libglib-2.0.so.0
#33 0x00007ffff61f5c01 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/qt5/lib/libQt5Core.so.5
#34 0x00007ffff61a167b in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/qt5/lib/libQt5Core.so.5
#35 0x00007ffff61a92e2 in QCoreApplication::exec() ()
   from /usr/lib/qt5/lib/libQt5Core.so.5
#36 0x00000000004230e3 in ?? ()
#37 0x00007ffff5a5308e in __libc_start_main () from /lib/libc.so.6
#38 0x00000000004231ba in _start ()
(gdb)

**Comment by attuska** [comment]
Ez glibc hiba lesz, mert UBK4-dev -en működik a glibc-2.30-al

**Comment by attuska** [comment]
glibc hiba, nem lesz kijavítva.

**Comment by attuska** [comment]
Mégsem glibc hiba, mert most már működik!
