### ISSUE TITLE
cinnamon-settings python hiba

### ISSUE THREAD

**Issue by attuska** [uhulinux/ub-ubk3#84]
>ttila@attila-pc:~$ cinnamon-settings
Traceback (most recent call last):
  File "/usr/share/cinnamon/cinnamon-settings/cinnamon-settings.py", line 724, in <module>
    window = MainWindow()
  File "/usr/share/cinnamon/cinnamon-settings/cinnamon-settings.py", line 307, in __init__
    for module in modules:
  File "/usr/share/cinnamon/cinnamon-settings/modules/cs_calendar.py", line 6, in <module>
    import pytz
ModuleNotFoundError: No module named 'pytz'
attila@attila-pc:~$

**Comment by attuska** [comment]
A python3-pytz feltelepítése után:
>attila@attila-pc:~$ cinnamon-settings
Traceback (most recent call last):
  File "/usr/share/cinnamon/cinnamon-settings/cinnamon-settings.py", line 724, in <module>
    window = MainWindow()
  File "/usr/share/cinnamon/cinnamon-settings/cinnamon-settings.py", line 307, in __init__
    for module in modules:
  File "/usr/share/cinnamon/cinnamon-settings/modules/cs_calendar.py", line 10, in <module>
    gi.require_version('TimezoneMap', '1.0')
  File "/usr/lib/python3.7/site-packages/gi/__init__.py", line 129, in require_version
    raise ValueError('Namespace %s not available' % namespace)
ValueError: Namespace TimezoneMap not available
attila@attila-pc:~$

**Comment by attuska** [comment]
https://github.com/uhulinux/ub-ubk3/commit/6aaed3eb248dbb95c13693b3206edf3bd09ac033
