### ISSUE TITLE
cinnamon-settings module bugs

### ISSUE THREAD

**Issue by attuska** [uhulinux/ub-ubk3#85]
Téma modul:
>attila@attila-pc:~$ cinnamon-settings
True
Using pam module (python3-pampy)
Loading Themes module
Traceback (most recent call last):
  File "/usr/share/cinnamon/cinnamon-settings/cinnamon-settings.py", line 667, in button_press
    self.side_view_nav(widget, None, category)
  File "/usr/share/cinnamon/cinnamon-settings/cinnamon-settings.py", line 171, in side_view_nav
    self.go_to_sidepage(cat, filtered_path, user_action=True)
  File "/usr/share/cinnamon/cinnamon-settings/cinnamon-settings.py", line 186, in go_to_sidepage
    sidePage.build()
  File "/usr/share/cinnamon/cinnamon-settings/bin/SettingsWidgets.py", line 213, in build
    self.module.on_module_selected()
  File "/usr/share/cinnamon/cinnamon-settings/modules/cs_themes.py", line 118, in on_module_selected
    widget.sync_initial_switch_state()
  File "/usr/share/cinnamon/cinnamon-settings/bin/CinnamonGtkSettings.py", line 194, in sync_initial_switch_state
    if editor.get_declaration(self.selector, decl_name):
  File "/usr/share/cinnamon/cinnamon-settings/bin/CinnamonGtkSettings.py", line 114, in get_declaration
    rs = self.get_ruleset(selector)
  File "/usr/share/cinnamon/cinnamon-settings/bin/CinnamonGtkSettings.py", line 105, in get_ruleset
    if rs.selector.as_css() == selector_css:
AttributeError: 'ImportRule' object has no attribute 'selector'
attila@attila-pc:~$

**Comment by attuska** [comment]
Van még a naptár modulban is hiba:
>Loading Calendar module
Traceback (most recent call last):
  File "/usr/share/cinnamon/cinnamon-settings/cinnamon-settings.py", line 667, in button_press
    self.side_view_nav(widget, None, category)
  File "/usr/share/cinnamon/cinnamon-settings/cinnamon-settings.py", line 171, in side_view_nav
    self.go_to_sidepage(cat, filtered_path, user_action=True)
  File "/usr/share/cinnamon/cinnamon-settings/cinnamon-settings.py", line 186, in go_to_sidepage
    sidePage.build()
  File "/usr/share/cinnamon/cinnamon-settings/bin/SettingsWidgets.py", line 213, in build
    self.module.on_module_selected()
  File "/usr/share/cinnamon/cinnamon-settings/modules/cs_calendar.py", line 36, in on_module_selected
    self.tz_selector = TimeZoneSelector()
  File "/usr/share/cinnamon/cinnamon-settings/modules/cs_calendar.py", line 227, in __init__
    for tz in pytz.common_timezones:
AttributeError: module 'pytz' has no attribute 'common_timezones'
attila@attila-pc:~$

**Comment by attuska** [comment]
Enerkiakezelő modul hiba:
>Loading Power module
Traceback (most recent call last):
  File "/usr/share/cinnamon/cinnamon-settings/cinnamon-settings.py", line 667, in button_press
    self.side_view_nav(widget, None, category)
  File "/usr/share/cinnamon/cinnamon-settings/cinnamon-settings.py", line 171, in side_view_nav
    self.go_to_sidepage(cat, filtered_path, user_action=True)
  File "/usr/share/cinnamon/cinnamon-settings/cinnamon-settings.py", line 186, in go_to_sidepage
    sidePage.build()
  File "/usr/share/cinnamon/cinnamon-settings/bin/SettingsWidgets.py", line 213, in build
    self.module.on_module_selected()
  File "/usr/share/cinnamon/cinnamon-settings/modules/cs_power.py", line 133, in on_module_selected
    device_types = [x[UP_TYPE] for x in self.csd_power_proxy.GetDevices()]
  File "/usr/lib/python3.7/site-packages/gi/overrides/Gio.py", line 354, in __call__
    None)
gi.repository.GLib.Error: g-dbus-error-quark: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name org.cinnamon.SettingsDaemon.Power was not provided by any .service files (2)
attila@attila-pc:~$

**Comment by attuska** [comment]
A pár órája kijött cinnamon-4.4.2 -ben az energiakezelő modul már működik.
A cinnamon-4.2.4 -ben és a 4.4.0 -ban a naptár modul is jó, a téma modul már a 4.4.2 -ben sem működik. A téma modulra egy zárt issue -t találtam ( https://github.com/linuxmint/cinnamon/issues/8969) az ottani ajánlás most nem működik. Talán egy új felhasználóval?

A 4.4.2-ben:
>attila@attila-pc:~$ cinnamon-settings
True
Using pam module (python3-pampy)
Loading Themes module
Traceback (most recent call last):
  File "/usr/share/cinnamon/cinnamon-settings/cinnamon-settings.py", line 667, in button_press
    self.side_view_nav(widget, None, category)
  File "/usr/share/cinnamon/cinnamon-settings/cinnamon-settings.py", line 171, in side_view_nav
    self.go_to_sidepage(cat, filtered_path, user_action=True)
  File "/usr/share/cinnamon/cinnamon-settings/cinnamon-settings.py", line 186, in go_to_sidepage
    sidePage.build()
  File "/usr/share/cinnamon/cinnamon-settings/bin/SettingsWidgets.py", line 213, in build
    self.module.on_module_selected()
  File "/usr/share/cinnamon/cinnamon-settings/modules/cs_themes.py", line 118, in on_module_selected
    widget.sync_initial_switch_state()
  File "/usr/share/cinnamon/cinnamon-settings/bin/CinnamonGtkSettings.py", line 194, in sync_initial_switch_state
    if editor.get_declaration(self.selector, decl_name):
  File "/usr/share/cinnamon/cinnamon-settings/bin/CinnamonGtkSettings.py", line 114, in get_declaration
    rs = self.get_ruleset(selector)
  File "/usr/share/cinnamon/cinnamon-settings/bin/CinnamonGtkSettings.py", line 105, in get_ruleset
    if rs.selector.as_css() == selector_css:
AttributeError: 'ImportRule' object has no attribute 'selector'
Loading Calendar module
Traceback (most recent call last):
  File "/usr/share/cinnamon/cinnamon-settings/cinnamon-settings.py", line 667, in button_press
    self.side_view_nav(widget, None, category)
  File "/usr/share/cinnamon/cinnamon-settings/cinnamon-settings.py", line 171, in side_view_nav
    self.go_to_sidepage(cat, filtered_path, user_action=True)
  File "/usr/share/cinnamon/cinnamon-settings/cinnamon-settings.py", line 186, in go_to_sidepage
    sidePage.build()
  File "/usr/share/cinnamon/cinnamon-settings/bin/SettingsWidgets.py", line 213, in build
    self.module.on_module_selected()
  File "/usr/share/cinnamon/cinnamon-settings/modules/cs_calendar.py", line 36, in on_module_selected
    self.tz_selector = TimeZoneSelector()
  File "/usr/share/cinnamon/cinnamon-settings/modules/cs_calendar.py", line 227, in __init__
    for tz in pytz.common_timezones:
AttributeError: module 'pytz' has no attribute 'common_timezones'
Loading Power module
Power module brightness page not available: GDBus.Error:org.gtk.GDBus.UnmappedGError.Quark._csd_5fpower_5fmanager_5ferror.Code0: csd-backlight-helper failed: Could not get or set the value of the backlight: No backlight devices present
>
>attila@attila-pc:~$

**Comment by attuska** [comment]
A 4.4.2 -ben újabb modulhiba jött helyes jelszómegadás ellenére:
>attila@attila-pc:~$ cinnamon-settings-users
==== AUTHENTICATING FOR org.cinnamon.settings-users ====
Users and Groups
Authenticating as: root
Password: 
polkit-agent-helper-1: error response to PolicyKit daemon: GDBus.Error:org.freedesktop.PolicyKit1.Error.Failed: No session for cookie
==== AUTHENTICATION FAILED ====
Error executing command as another user: Not authorized
>
>This incident has been reported.
attila@attila-pc:~$

**Comment by attuska** [comment]
ubk2 -n minden működik.

**Comment by attuska** [comment]
A ~/.config/gtk-3.0 mappát átnevezve helyrejött.
A hiba az én készülékemben volt.

**Comment by attuska** [comment]
Újból nem nyílt meg a téma beállítás.
A ~/.config/gtk-3.0 -ba valami elhelyezett a bookmarks fájl mellé egy gtk.css fájlt és egy colors.css fájlt.
Nyilván a colors.css fájlban van valami, a mi a téma választást megakadályozza. Ezt a colors.css fájlt nem a cinnamon helyezi el, hanem valami más desktop.
Átneveztem a mappát és ezután újra indítva a cinnamont már ismét működik a téma választás. A cinnamon létrehozta újból és belérakott egy magányos bookmarks fájl.t

**Comment by attuska** [comment]
Nos, megvan a bűnös!
A ~/.config/colors.css és gtk.css fájlokat a plasma munkamenet helyezi el, az elhelyezett fájlokat letörölve a cinnamon újra témázható.
A plasma magasan tojik a cinnamon munkamenet használhatóságára, illetve a cinnamon nem jól kezeli ezen fájlok létét. Lehet, hogy érdemes lehetne ezt a hibát a plasma, vagy a cinnamon fejlesztőknek jelezni, mert most már atombiztosan reprodukálható a hiba.

**Comment by attuska** [comment]
A téma "megoldva". https://github.com/uhulinux/ub-ubk3/commit/85ce32a6e46fbe51255ebe0ac6eee8baf1f1ae22
