### ISSUE TITLE
calibre hibásan működik

### ISSUE THREAD

**Issue by attuska** [uhulinux/ub-ubk3#90]
El sem indul, python hibával elszáll természetesen.

> attila@attila-pc:~$ calibre
Traceback (most recent call last):
  File "/bin/calibre", line 20, in <module>
    sys.exit(calibre())
  File "/usr/lib/calibre/calibre/gui_launch.py", line 73, in calibre
    main(args)
  File "/usr/lib/calibre/calibre/gui2/main.py", line 558, in main
    gui_debug=gui_debug)
  File "/usr/lib/calibre/calibre/gui2/main.py", line 384, in run_gui
    from calibre.gui2.ui import Main
  File "/usr/lib/calibre/calibre/gui2/ui.py", line 42, in <module>
    from calibre.gui2.init import LibraryViewMixin, LayoutMixin
  File "/usr/lib/calibre/calibre/gui2/init.py", line 20, in <module>
    from calibre.gui2.book_details import BookDetails
  File "/usr/lib/calibre/calibre/gui2/book_details.py", line 19, in <module>
    from calibre.ebooks.metadata.book.render import mi_to_html
  File "/usr/lib/calibre/calibre/ebooks/metadata/book/render.py", line 16, in <module>
    from calibre.library.comments import comments_to_html, markdown
  File "/usr/lib/calibre/calibre/library/comments.py", line 11, in <module>
    from calibre.ebooks.BeautifulSoup import (
  File "/usr/lib/calibre/calibre/ebooks/BeautifulSoup.py", line 7, in <module>
    import bs4
ImportError: No module named bs4
attila@attila-pc:~$

**Comment by attuska** [comment]
A legújabb python3 portja már elindult a műtőasztalon, de egy rakás újabb python3 csomag kell neki.

python3-soupsieve
python3-regex
python3-css-parser
python3-beautifulsoup (ez a 4-es!)
python3-mechanize

És ez még csak a kezdet, mert ezzekkel már legalább elindul, de gyakorlatban semmit nem lehet letöltetni vele, mert minden kísérlet így végződik:
 

> interface language: hu
Traceback (most recent call last):
  File "/usr/lib/calibre/calibre/gui2/dialogs/choose_format.py", line 100, in accept
    self._format = self._formats[self.formats.currentRow()]
TypeError: 'dict_keys' object is not subscriptable

A beépített olvasó használati kísérlet így végződik:

>Traceback (most recent call last):
  File "/usr/bin/calibre-parallel", line 20, in <module>
    sys.exit(main())
  File "/usr/lib/calibre/calibre/utils/ipc/worker.py", line 208, in main
    result = func(*args, **kwargs)
  File "/usr/lib/calibre/calibre/gui_launch.py", line 79, in ebook_viewer
    from calibre.gui2.viewer.main import main
  File "/usr/lib/calibre/calibre/gui2/viewer/main.py", line 11, in <module>
    from PyQt5.QtWebEngineCore import QWebEngineUrlScheme
ModuleNotFoundError: No module named 'PyQt5.QtWebEngineCore'

A python3-pyqtwebengine kellene, de ez egyelőre elkészíthetetlen, mert ez sip5 el a sip-build -ot használná a csomagjához. Tehát kellene a sip5, a python3-toml, python3-pyqtbuild is, de ekkor is összetojja magát:

> compile...
> python3 configure.py --no-dist-info --verbose -c -j 3 -q //usr/lib/qt5/bin/qmake --pyqt-sipdir=/usr/share/sip/Py3-PyQt5/QtCore/
Error: Unable to create the C++ code.
Configuring PyQtWebEngine 5.14.0...
The PyQtWebEngine .sip files will be installed in
/usr/share/sip/Py3-PyQt5/QtCore.
PyQtWebEngine will be installed in /usr/lib/python3.7/site-packages/PyQt5.
PyQt 5.13.2 is being used.
Qt 5.14.0 is being used.
sip 4.19.19 is being used.
The sip executable is /bin/sip.
PyQtWebEngine is being built with 'protected' redefined as 'public'.
The PEP 484 stubs will be installed in /usr/lib/python3.7/site-packages/PyQt5.
The QScintilla API file will be installed in /usr/lib/qt5/qsci/api/python.
Generating the C++ source for the QtWebEngine module...
/bin/sip -I /var/uhubuild/work/compile/sip -I /usr/share/sip/Py3-PyQt5/QtCore -n PyQt5.sip -t WS_X11 -t Qt_5_14_0 -B Qt_6_0_0 -t QtWebEngine_5_14_0 -y QtWebEngine.pyi -a QtWebEngine.api -P -o -j 3 -c /var/uhubuild/work/compile/QtWebEngine /var/uhubuild/work/compile/sip/QtWebEngine/QtWebEnginemod.sip
sip: Deprecation warning: the -B flag is deprecated
sip: Unable to find file "QtCore/QtCoremod.sip"
HIBA a(z) compile fazisban

Tehát a python-pyqt5 csomagban meglévőt nem leli, mert rossz helyen keresi.

> attila@attila-pc:~/pkg/UBK3/main/amd64$ zgrep QtCore/QtCoremod.sip Contents.gz
python2-pyqt5:   0   0  f  644     6850 /usr/share/sip/Py2-PyQt5/QtCore/QtCoremod.sip
python3-pyqt5:   0   0  f  644     6850 /usr/share/sip/Py3-PyQt5/QtCore/QtCoremod.sip
attila@attila-pc:~/pkg/UBK3/main/amd64$

**Comment by attuska** [comment]
Hajlok rá, hogy kidobjam ezt a calibre csomagot, vagy kiváltsam a forrásból való készítéstét egy calibre installerrel.
A python2 -es most nem megy, a leendő python3 -as meg döcög.

**Comment by attuska** [comment]
Már működik, de még nem az igazi.
https://github.com/uhulinux/ub-ubk3/commit/c8d862b91b1c86b7288a66d92a4644f3c66b6711

**Comment by attuska** [comment]
Már működik a beépített olvasó.
https://github.com/uhulinux/ub-ubk3/commit/cacfc875c8baf6b42b47daa17cc3ceb53ee256a3
A könyv letöltés még mindig hibás:

> TypeError: 'dict_keys' object is not subscriptable

A hírolvasó nem működik a python3-feedparser felrakása után sem. Aszondja, hogy nincs feedparser modul! Ezért egyelőre értelmetlen a python3-feedparser csomag, mert nem tudja használni.

Azért ez már haladás.

**Comment by attuska** [comment]
Egyelőre csináltam egy csomagot a "mindent bele" módon előre lefordított bináris halmazból.
A csomag neve calibre-bin lett, ez jónak tűnik, ezért lezárom az issue -t.
https://github.com/uhulinux/ub-ubk3/commit/21c548570f310debf62f77acfd199e5886876f1c
