### ISSUE TITLE
0install nem indul

### ISSUE THREAD

**Issue by attuska** [uhulinux/ub-ubk3#99]
A legújabb fordításához már egy rakás ocaml cucc kellne. https://github.com/0install/0install/blob/master/README.md
A mienk python3 -as már az UBK1 óta és változatlan verziójú és mindegyik így végzi:
>attila@attila-pc:~$ 0desktop --manage
Traceback (most recent call last):
  File "/bin/0desktop", line 14, in <module>
    desktop.main(sys.argv[1:])
  File "/usr/lib/python3.7/site-packages/zeroinstall/gtkui/desktop.py", line 62, in main
    from zeroinstall.gtkui.applistbox import AppListBox, AppList
  File "/usr/lib/python3.7/site-packages/zeroinstall/gtkui/applistbox.py", line 6, in <module>
    from zeroinstall.support.tasks import get_loop
  File "/usr/lib/python3.7/site-packages/zeroinstall/support/tasks.py", line 462
    def async(fn):
            ^
SyntaxError: invalid syntax
attila@attila-pc:~$ 
Python2 -re fordítva elindul, de nem sok haszna van, így jogosnak tűnik a leendő UBK5 esetén a kidobása.
Ez a szintaxis hiba azért bosszantó, mert a 2to3 szerint rendben van a tasks.py.

**Comment by attuska** [comment]
Találtam valamit, az async foglalt keyword, nem definiálható python3 -ban!

**Comment by attuska** [comment]
Már megy, de minek?
https://github.com/uhulinux/ub-ubk3/commit/5848e33d4cd5b0c688c68515f2156c0ad1b5d3cf
